#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/v1/login
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path:       /api/v1/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
 